definitions:
  environment:
    shared_env: &shared_env
      flutter: 3.24.1
      groups:
        - shorebird
        - app_store
    vars:
      BUNDLE_ID: dev.shorebird.codemagic-demo
  scripts:
    - &shorebird_setup
      name: Shorebird Setup
      script: |
        # Install Shorebird
        curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash

        # Add Shorebird to PATH
        echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV
    - &ios_initialize_keychain
      name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
      script: |
        keychain initialize
    - &fetch_signing_files
      name: Fetch signing files
      script: |
        app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create --issuer-id "$ISSUER_ID"
    - &add_certs_to_keychain
      name: Add certs to keychain
      script: |
        keychain add-certificates
    - &use_profiles
      name: Set up code signing settings on Xcode project
      script: |
        xcode-project use-profiles
    - &flutter_setup
      name: Flutter Setup
      script: |
        flutter pub get
        flutter analyze
        flutter test

workflows:
  release-android-workflow:
    name: Release Android
    instance_type: mac_mini_m1
    environment:
      <<: *shared_env
    scripts:
      - *shorebird_setup
      - *flutter_setup
      - name: Shorebird Release
        script: |
          shorebird release android
  release-ios-workflow:
    name: Release iOS
    instance_type: mac_mini_m1
    environment:
      <<: *shared_env
      ios_signing:
        distribution_type: app_store
        bundle_identifier: dev.shorebird.codemagic-demo
    scripts:
      - *shorebird_setup
      - *flutter_setup
      - *ios_initialize_keychain
      - *fetch_signing_files
      - *add_certs_to_keychain
      - *use_profiles
      - name: Shorebird Release
        script: |
          shorebird release ios
  patch-android-workflow:
    name: Patch Android
    instance_type: mac_mini_m1
    environment:
      <<: *shared_env
    inputs:
      release_version:
        description: The release version to patch
    scripts:
      - *shorebird_setup
      - *flutter_setup
      - name: Shorebird Patch
        script: shorebird patch android --release-version=${{ inputs.release_version }}
  patch-ios-workflow:
    name: Patch iOS
    instance_type: mac_mini_m1
    environment:
      <<: *shared_env
      ios_signing:
        distribution_type: app_store
        bundle_identifier: dev.shorebird.codemagic-demo
    inputs:
      release_version:
        description: The release version to patch
    scripts:
      - *shorebird_setup
      - *flutter_setup
      - *ios_initialize_keychain
      - *fetch_signing_files
      - *add_certs_to_keychain
      - *use_profiles
      - name: Shorebird Patch
        script: |
          shorebird patch ios --release-version=${{ inputs.release_version }}
