definitions:
  scripts:
    - &shorebird_setup
      name: Shorebird Setup
      script: |
        # Install Shorebird
        curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash

        # Add Shorebird to PATH
        echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV

    - &flutter_setup
      name: Flutter Setup
      script: |
        flutter pub get
        flutter analyze
        flutter test

workflows:
  release-android-workflow:
    name: Release Android
    instance_type: mac_mini_m1
    environment:
      flutter: 3.24.1
      groups:
        - shorebird
    scripts:
      - *shorebird_setup
      - *flutter_setup
      - name: Shorebird Release
        script: |
          shorebird release android
  patch-android-workflow:
    name: Patch Android
    instance_type: mac_mini_m1
    environment:
      groups:
        - shorebird
    scripts:
      - *shorebird_setup
      - *flutter_setup
      - name: Shorebird Patch
        script: shorebird patch android
  patch-ios-workflow:
    name: Patch iOS
    instance_type: mac_mini_m1
    environment:
      flutter: 3.24.1
      groups:
        - shorebird
    scripts:
      - *shorebird_setup
      - *flutter_setup
      - name: Shorebird Patch
        script: |
          shorebird patch ios
