name: codemagic_demo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - shorebird.yaml
  uses-material-design: true
